site_name: NGI Reports
repo_url: https://github.com/NationalGenomicsInfrastructure/ngi_reports/
site_description: Package to generate reports for NGI Stockholm
site_author: Phil Ewels
theme: flatly
pages:
- ['index.md', 'Introduction']
- ['installation.md', 'Installation']
- ['usage.md', 'Usage']
- ['contributing.md', 'Contributing']
- ['report_project_report.md', 'Project Reports']
