name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        STATUS_DB_CONFIG: ${GITHUB_WORKSPACE}/test/dummy_statusdb.yaml
    strategy:
      matrix:
        python-version: [3.5, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
    - name: Echo variables
      run: |
        echo "Home: ${HOME}"
        echo "STATUS_DB_CONFIG: ${STATUS_DB_CONFIG}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
    - name: Test with unittest
      run: |
        cd test; python -m unittest test_project_progress.py
